### ISSUE TITLE
Hi your demo site appears to be down.

### ISSUE THREAD

**Issue by cmh234** [PROSLab/BPMN-Redrawer#4]

**Comment by FabrizioFornari** [comment]
Dear Chris,

Thank you for pointing that out.

We are currently working on that, the site should come back up in the upcoming days.

Regards

**Comment by cmh234** [comment]
Ok, thank you. I am trying to get it to run on my Dev workstation. When installing and starting the frontend, I'm getting this error.

C:\Sites\BPMN-Redrawer\frontend>npm run lint

> bpmn_redrawer@0.0.1 lint
> eslint --ext .js,.ts,.vue ./


C:\Sites\BPMN-Redrawer\frontend\server.js
  1:17  error  Require statement not part of import statement  @typescript-eslint/no-var-requires
  2:21  error  Require statement not part of import statement  @typescript-eslint/no-var-requires

✖ 2 problems (2 errors, 0 warnings)


C:\Sites\BPMN-Redrawer\frontend>quasar build

 Build mode........ spa
 Quasar theme...... mat
 Quasar CLI........ v0.17.26
 Quasar Framework.. v0.17.20
 Debugging......... no

 app:quasar-conf Reading quasar.conf.js +0ms

⚠️  Quasar CLI requires a minor change to the root component:
   C:\Sites\BPMN-Redrawer\frontend\src\App.vue

  Please add: id="q-app" (or write #q-app if using Pug)
  to the outermost HTML element of the template.

Example:
  <template>
    <div id="q-app">
      ...
    </div>
  </template>

**Comment by cmh234** [comment]
I added `<!-- id="q-app" -->` before the template tag in App.vue , and the CLI stopped complaining.

Now I'm getting this error. index.ts exist but not index.js. /quasar.config.js and /tsconfig.json below


```

C:\Sites\BPMN-Redrawer\frontend>quasar dev

 Dev mode.......... spa
 Quasar theme...... mat
 Quasar CLI........ v0.17.26
 Quasar Framework.. v0.17.20
 Debugging......... enabled

 app:quasar-conf Reading quasar.conf.js +0ms
 app:dev Checking listening address availability (0.0.0.0:7000)... +10ms
(node:36512) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
node:fs:594
  handleErrorFromBinding(ctx);
  ^

[  Error: ENOENT: no such file or directory, open 'C:\Sites\BPMN-Redrawer\frontend\src\router\index.js'

```

quasar.conf.js

```
module.exports = configure(function (ctx) {
  return {
    // https://quasar.dev/quasar-cli/supporting-ts
    supportTS: {
      tsCheckerConfig: {
        eslint: {
          enabled: true,
          files: './src/**/*.{ts,tsx,js,jsx,vue}',
        },
      },
    },
```

tsconfig.json
```

{
  "extends": "@quasar/app/tsconfig-preset",
  "compilerOptions": {
    "baseUrl": ".",
    "strictNullChecks": true
  }
}

```

**Comment by FabrizioFornari** [comment]
The server is up and running
